spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    default: development
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs