spring:
  datasource:
    url: jdbc:h2:mem:TaskManager;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console.enabled: true
  output:
    ansi:
      enabled: always
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem